version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      day: sunday
      time: "01:00"
    labels:
      - scope:dependency
    target-branch: "main"
